
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package yylexmain;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int parc = 13;
  public static final int para = 12;
  public static final int constfloat = 4;
  public static final int coma = 15;
  public static final int floatt = 19;
  public static final int voidd = 17;
  public static final int llavc = 21;
  public static final int llava = 20;
  public static final int menos = 7;
  public static final int intt = 18;
  public static final int constlit = 5;
  public static final int ident = 2;
  public static final int rest = 11;
  public static final int div = 10;
  public static final int igual = 16;
  public static final int EOF = 0;
  public static final int constint = 3;
  public static final int returnn = 22;
  public static final int coment = 6;
  public static final int error = 1;
  public static final int puntc = 14;
  public static final int mul = 9;
  public static final int mas = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ident",
  "constint",
  "constfloat",
  "constlit",
  "coment",
  "menos",
  "mas",
  "mul",
  "div",
  "rest",
  "para",
  "parc",
  "puntc",
  "coma",
  "igual",
  "voidd",
  "intt",
  "floatt",
  "llava",
  "llavc",
  "returnn"
  };
}

